apiVersion: v1
kind: Service
metadata:
  name: {{ include "soketi.fullname" . }}-peer
  labels:
    {{- include "soketi.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.peerServer.service.port }}
      targetPort: {{ .Values.peerServer.service.port }}
      protocol: TCP
      name: peer
  selector:
    {{- include "soketi.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "soketi.fullname" . }}-peer-headless
  labels:
    {{- include "soketi.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.peerServer.service.port }}
      targetPort: {{ .Values.peerServer.service.port }}
      protocol: TCP
      name: peer
  selector:
    {{- include "soketi.selectorLabels" . | nindent 4 }}
