{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "soketi.serviceAccountName" . }}
  labels:
    app.kubernetes.io/component: controller
    {{- include "soketi.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - patch
  - apiGroups: [""]
    resources:
      - events
    verbs:
      - create
  - apiGroups:
    - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "soketi.serviceAccountName" . }}
  labels:
    app.kubernetes.io/component: controller
    {{- include "soketi.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "soketi.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "soketi.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
